# Description

This is my note for comparison Numpy and Torch

In [1]:
import numpy as np
import torch

## Zeros

This is the same with `ones`, for `numpy`, it can build the array with user-defined data structure, such as the following one: 


In [6]:
rain_drops = np.zeros(5, dtype=[('position', float, (2,)),
                                      ('size',     float),
                                      ('growth',   float),
                                      ('color',    float, (4,))])
rain_drops


array([([0., 0.], 0., 0., [0., 0., 0., 0.]),
       ([0., 0.], 0., 0., [0., 0., 0., 0.]),
       ([0., 0.], 0., 0., [0., 0., 0., 0.]),
       ([0., 0.], 0., 0., [0., 0., 0., 0.]),
       ([0., 0.], 0., 0., [0., 0., 0., 0.])],
      dtype=[('position', '<f8', (2,)), ('size', '<f8'), ('growth', '<f8'), ('color', '<f8', (4,))])

With the user-defined structure, you can easily use the data with new indexing method ["name"]

In [7]:
rain_drops["position"]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

But, according to my knowledge, there is no such usage in `pytorch`.

I will define two class for saving data, you can feel the difference, and of course, the convenience of the self-defined structure in `numpy`

In [8]:
class save_np:
    'this class is used for save the data, in which nx, ny stands for the mesh size, nt is the total number of time step, dt is the size of time step'
    def __init__(self,nx,ny,dt,nt):
        self.T_total=int(100*dt*nt)#muliplying 100 makes T is in milliseconds
        self.save=np.zeros(self.T_total,dtype=[("u",float,(nx,ny)),
        ("v",float,(nx,ny)),("p",float,(nx,ny))])
    
    "this function is used to record the data"
    def record(self,i,u_in,v_in,p_in):
        self.save["u"][i]=u_in
        self.save["v"][i]=v_in
        self.save["p"][i]=p_in

    def out(self):
        return self.save

In [9]:
u1=np.arange(16).reshape(4,4)
v1=np.ones([4,4])
p1=np.zeros([4,4])

u2=2*np.ones([4,4])
v2=3*np.ones([4,4])
p2=4*np.ones([4,4])

u3=-2*torch.ones([4,4])
v3=-3*torch.ones([4,4])
p3=-4*torch.ones([4,4])

In [18]:
s1=save_np(4,4,0.1,1)
s1.record(0,u1,v1,p1)
s1.record(1,u2,v2,p2)
s1.record(2,u3,v3,p3)

all=s1.out()
all["u"]

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]],

       [[ 2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.]],

       [[-2., -2., -2., -2.],
        [-2., -2., -2., -2.],
        [-2., -2., -2., -2.],
        [-2., -2., -2., -2.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., 

In [20]:
class save_torch:
    'this class is used for save the data'
    def __init__(self,nx,ny,dt,nt):
        self.T_total=int(100*dt*nt)
        self.u_save=torch.zeros([self.T_total,nx,ny],dtype=torch.float32)
        self.v_save=torch.zeros([self.T_total,nx,ny],dtype=torch.float32)
        self.p_save=torch.zeros([self.T_total,nx,ny],dtype=torch.float32)

    def record(self,i,u_in,v_in,p_in):
        self.u_save[i]=u_in
        self.v_save[i]=v_in
        self.p_save[i]=p_in

    def out(self):
        return self.u_save,self.v_save,self.p_save

In [19]:
#torch can't save array, so all the data should be tensor
ut1=torch.arange(16).reshape(4,4)
vt1=torch.ones([4,4])
pt1=torch.zeros([4,4])

ut2=2*torch.ones([4,4])
vt2=3*torch.ones([4,4])
pt2=4*torch.ones([4,4])

ut3=-2*torch.ones([4,4])
vt3=-3*torch.ones([4,4])
pt3=-4*torch.ones([4,4])

In [21]:
s2=save_torch(4,4,0.1,1)
s2.record(2,u3,v3,p3)

u,v,p=s2.out()
u

tensor([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[-2., -2., -2., -2.],
         [-2., -2., -2., -2.],
         [-2., -2., -2., -2.],
         [-2., -2., -2., -2.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0., 

## roll

There is only a small different, the last parameter (the axis/dimensions to be rolled)

For [`numpy`](https://numpy.org/doc/stable/reference/generated/numpy.roll.html), the parameters in `roll` is axis, for [`torch`](https://pytorch.org/docs/stable/generated/torch.roll.html), the parameters in function `roll` is the dims

In [2]:
torch_origin=torch.arange(12).reshape(3,4)
torch_origin

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [25]:
torch.roll(torch_origin,-1,dims=1)

tensor([[ 1,  2,  3,  0],
        [ 5,  6,  7,  4],
        [ 9, 10, 11,  8]])

In [22]:
np_origin=np.arange(12).reshape(3,4)
np_origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.roll(np_origin,-1,axis=1)

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  4],
       [ 9, 10, 11,  8]])

## copy()

For numpy, the function [`copy()`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html) is helpful, and for torch, you should use the function [`clone()`](https://pytorch.org/docs/stable/generated/torch.clone.html)

In [7]:
np_origin=np.arange(12)
np_copy1=np.copy(np_origin)
np_copy2=np_origin.copy()

In [8]:
torch_origin=torch.arange(12)
torch_copy1=torch.clone(torch_origin)
#or
torch_copy2=torch_origin.clone()


## random

`np.random.rand`=`torch.rand`

In [2]:
np_rand=np.random.rand(2)
np_rand

array([0.53962225, 0.58631117])

In [3]:
torch_rand=torch.rand(2)
torch_rand

tensor([0.8484, 0.6812])

## meshgrid

For [numpy](https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html), the index is set as the 'xy' as default. While for [torch](https://pytorch.org/docs/stable/generated/torch.meshgrid.html), the indexing need to specify. (According to the documents, in future, `torch.meshgrid` will transition to indexing=’xy’ as the default)

In [6]:
h,w=2,3
x_np,y_np=np.meshgrid(np.arange(w),np.arange(h))
xy_np=np.stack([x_np,y_np],axis=-1)
print(xy_np.shape)
(x_np,y_np)

(2, 3, 2)


(array([[0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1]]))

In [12]:
x_torch,y_torch=torch.meshgrid(torch.arange(w),torch.arange(h), indexing='xy')
xy_torch=torch.stack([x_torch,y_torch],axis=-1)
print(xy_torch.shape)
(x_torch,y_torch)

torch.Size([3, 2, 2])


(tensor([[0, 0],
         [1, 1],
         [2, 2]]),
 tensor([[0, 1],
         [0, 1],
         [0, 1]]))