In [1]:
# sphinx_gallery_thumbnail_path = "../../gallery/assets/transforms_thumbnail.png"

from PIL import Image
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

import torch
import torchvision.transforms as T


plt.rcParams["savefig.bbox"] = 'tight'
orig_img = Image.open(Path('assets') / 'astronaut.jpg')
# if you change the seed, make sure that the randomly-applied transforms
# properly show that the image can be both transformed and *not* transformed!
torch.manual_seed(0)


def plot(imgs, with_orig=True, row_title=None, **imshow_kwargs):
    if not isinstance(imgs[0], list):
        # Make a 2d grid even if there's just 1 row
        imgs = [imgs]

    num_rows = len(imgs)
    num_cols = len(imgs[0]) + with_orig
    fig, axs = plt.subplots(nrows=num_rows, ncols=num_cols, squeeze=False)
    for row_idx, row in enumerate(imgs):
        row = [orig_img] + row if with_orig else row
        for col_idx, img in enumerate(row):
            ax = axs[row_idx, col_idx]
            ax.imshow(np.asarray(img), **imshow_kwargs)
            ax.set(xticklabels=[], yticklabels=[], xticks=[], yticks=[])

    if with_orig:
        axs[0, 0].set(title='Original image')
        axs[0, 0].title.set_size(8)
    if row_title is not None:
        for row_idx in range(num_rows):
            axs[row_idx, 0].set(ylabel=row_title[row_idx])

    plt.tight_layout()

FileNotFoundError: [Errno 2] No such file or directory: 'assets\\astronaut.jpg'

In [28]:
import torch
from torchvision import transforms
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [8]:
a=torch.rand(3,8,8)
a*=10
a

tensor([[[5.1526, 8.6233, 1.7731, 8.2232, 6.6465, 8.0089, 4.2311, 7.1863],
         [8.7594, 1.7874, 7.2812, 1.8446, 8.4852, 9.5051, 0.9142, 4.2815],
         [4.0475, 5.4800, 4.9905, 3.1808, 5.3387, 6.8324, 7.1274, 8.4269],
         [0.8371, 6.0961, 9.2635, 4.7462, 1.1545, 0.4903, 6.0291, 7.5536],
         [4.1274, 2.1205, 8.7438, 3.9129, 9.1773, 8.0246, 7.7303, 8.0707],
         [5.3804, 2.2330, 2.8615, 8.3441, 9.5709, 2.8890, 1.9017, 6.8373],
         [7.3698, 6.3261, 2.4318, 1.8323, 8.6918, 3.0025, 9.2144, 0.9011],
         [5.0799, 7.7298, 5.4969, 4.5555, 0.4346, 8.0101, 8.8896, 9.9460]],

        [[6.7365, 8.8141, 5.1034, 1.5474, 7.5257, 6.9479, 4.7057, 5.1526],
         [5.4651, 8.8796, 1.9432, 8.8625, 3.8524, 0.2306, 9.2425, 1.9612],
         [9.6590, 8.6857, 9.2598, 9.1804, 4.0736, 1.0818, 2.9418, 5.8012],
         [2.7771, 7.5689, 2.9397, 2.4829, 0.8491, 9.4553, 7.6330, 9.0288],
         [2.5065, 7.4430, 9.4390, 2.0838, 3.5115, 0.6197, 9.0202, 4.4726],
         [2.4121, 2.085

In [13]:
class FigureDataset(Dataset):
    def __init__(self):
        self.Data=torch.tensor([[1,1],[2,2],[3,3],[4,4]])
        self.Label=torch.tensor([9,8,7,6])
    def __getitem__(self, index):
        image=self.Data[index]
        label=self.Label[index]
        return image, label
    def __len__(self):
        return len(self.Data)

In [88]:
aa=torch.ones(2,2,3)
aa[:,:,1:2]+=1
aa[:,:,2:3]+=2
aa[1,0,:]+=1
aa[0,1,:]*=2
aa[1,1,:]+=3
aa

tensor([[[1., 2., 3.],
         [2., 4., 6.]],

        [[2., 3., 4.],
         [4., 5., 6.]]])

In [95]:
aa[1]

tensor([[2., 3., 4.],
        [4., 5., 6.]])

In [67]:
transform1=torch.nn.Sequential(
    transforms.Normalize((0, 0.5), (1, 0.5))
)

In [33]:
transform2 = transforms.Compose(
#     [transforms.ToTensor(),
     [transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

In [90]:
b=transform1(aa)
b

tensor([[[ 1.,  2.,  3.],
         [ 2.,  4.,  6.]],

        [[ 3.,  5.,  7.],
         [ 7.,  9., 11.]]])

In [39]:
a.mean()

tensor(5.3196)

In [41]:
b.mean()

tensor(9.6393)

In [34]:
transform2(a)

tensor([[[ 9.3053, 16.2465,  2.5461, 15.4464, 12.2930, 15.0177,  7.4622,
          13.3726],
         [16.5187,  2.5749, 13.5625,  2.6892, 15.9705, 18.0101,  0.8283,
           7.5629],
         [ 7.0949,  9.9601,  8.9809,  5.3616,  9.6775, 12.6648, 13.2549,
          15.8539],
         [ 0.6742, 11.1923, 17.5270,  8.4924,  1.3089, -0.0193, 11.0583,
          14.1071],
         [ 7.2548,  3.2410, 16.4877,  6.8258, 17.3546, 15.0493, 14.4607,
          15.1415],
         [ 9.7607,  3.4661,  4.7230, 15.6882, 18.1418,  4.7781,  2.8034,
          12.6746],
         [13.7396, 11.6522,  3.8637,  2.6647, 16.3836,  5.0051, 17.4288,
           0.8022],
         [ 9.1597, 14.4596,  9.9938,  8.1110, -0.1309, 15.0202, 16.7792,
          18.8921]],

        [[12.4730, 16.6282,  9.2067,  2.0949, 14.0513, 12.8958,  8.4114,
           9.3052],
         [ 9.9301, 16.7591,  2.8864, 16.7251,  6.7048, -0.5388, 17.4850,
           2.9225],
         [18.3180, 16.3713, 17.5195, 17.3607,  7.1472,  1.1636,  4.8

In [26]:
torch.nn.transforms.ToTensor(a)

AttributeError: module 'torch.nn' has no attribute 'transforms'

In [19]:
FDataset=FigureDataset()
loader=DataLoader(FDataset,batch_size=2)

TypeError: __init__() got an unexpected keyword argument 'transform'