In [1]:
import torch
from torch import tensor

In [66]:

b=torch.ones(2,3,3)+1
c=torch.ones(1)

In [22]:
a-c

tensor([[0., 0.],
        [0., 0.]])

In [15]:
a.mul(b)

tensor([[2., 2.],
        [2., 2.]])

In [28]:
torch.matmul(a,b).shape

torch.Size([2, 3, 3])

In [59]:
b.shape

torch.Size([2, 3, 3])

In [67]:
a.squeeze().shape

torch.Size([3, 3])

In [60]:
d=b.unsqueeze(3)
d.shape

torch.Size([2, 3, 3, 1])

In [123]:
a=torch.ones(2,3)
a[1:,]-=1
b=torch.ones(2,3)+1

In [126]:
torch.cat((a,b),1).shape

torch.Size([2, 6])

In [128]:
torch.cat((a,b),0).shape

torch.Size([4, 3])

In [127]:
torch.stack((a,b),1).shape

torch.Size([2, 2, 3])

In [130]:
torch.stack((a,b),0).shap

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [97]:
a

tensor([[1., 1., 1.],
        [2., 2., 2.]])

In [73]:
torch.arange(1,5,1)


tensor([1, 2, 3, 4])

In [74]:
torch.linspace(1,5,10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])